version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: momo
      POSTGRES_PASSWORD: momo_password
      POSTGRES_DB: momo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U momo -d momo_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      POSTGRES_USER: momo
      POSTGRES_PASSWORD: momo_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: momo_db
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: